version: "3.9"

services:
  frontend:
    build:
      context: ./
    ports:
      - "5173:5173"
    container_name: frontend_container
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  mysql_data:
  node_modules:
